name: scheduled-python

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:         # optional: run manually from the Actions tab

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        env:
          KEY: ${{ secrets.KEY }}
          CHOW_ID: ${{ secrets.CHOW_ID }}
          CHOW_URL: ${{ secrets.CHOW_URL }}
        run: python chow.py
